### ISSUE TITLE
Problems trying to add additional request headers

### ISSUE THREAD

**Issue by slooker** [FormidableLabs/express-winston-middleware#10]
I'm trying to add to our request logging the size of the request and the amount of time the request took.  Our current logs look like this:

21:08:05 wedgies-api-staging-34           |  GET /question/_id/123456    200    9ms - 5.1kb

I'm trying to add the last 2 sections (the 9ms and 5.1kb).  I tried doing it like this to add the whole request:

    var Log = require("express-winston-middleware").Log;
    var log = new Log({
      transports: [
        new (winston.transports.Console)({ json: true })
      ]
    });
    var winMid = require("express-winston-middleware");
    // Cut express stuff
     app.use(new winMid.request({
       transports: [
         new (winston.transports.Console)({ json: true })
       ]
     }));
     // Hoping this adds the whole request (which I don't want, I just want to add time and size)
    // But this doesn't add anything either
    log.addReq(req);

But that obviously won't work since it's not part of the request logging.

I assume there's a way to do it, but I don't understand the docs for this.

**Comment by ryan-roemer** [comment]
When you're _using_ the request logger look to this https://github.com/FormidableLabs/express-winston-middleware#express-middleware and specifically this:

```
app.get("/foo", function (req, res) {
  res.locals._log.info("This is an extra manual log message!", {
    extra: "metadata"
  });
  // Rest of your code here...
});
```

The operative thing is the request logger is available as `res.locals._log` for each request. Add metadata to that, or log out extra messages as you see fit.

In your example above, you have a completely separate logger in the `log` variable. Typically you only instantiate like that for things for the server as a whole (like "server started up", "server failed", etc.)

**Comment by slooker** [comment]
Got it.  Thanks!
